# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whattp < Formula
  desc ""
  homepage "https://github.com/valxntine/whattp"
  version "0.1"

  on_macos do
    url "https://github.com/valxntine/whattp/releases/download/v0.1/whattp_0.1_darwin_all.tar.gz"
    sha256 "e447e7dcac119147d5cdb1a37516d920e75ce079559662cf3849f7c23f80f0c7"

    def install
      bin.install "whattp"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/valxntine/whattp/releases/download/v0.1/whattp_0.1_linux_arm64.tar.gz"
      sha256 "7d9c8698398d20f5f6bbfc9c22175dc88a6b705c125d8b13ba1d1abf9c00bb5d"

      def install
        bin.install "mediumautopost"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/valxntine/whattp/releases/download/v0.1/whattp_0.1_linux_amd64.tar.gz"
      sha256 "ddfa30371533ef6d45a147844395fc22577177d4b5e51bbfce19ffb7e5609623"

      def install
        bin.install "mediumautopost"
      end
    end
  end
end
